-- Login audit table and RPC for Supabase
-- Usage: run this SQL in Supabase SQL editor once.

create table if not exists public.login_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text,
  ip inet,
  user_agent text,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.login_events enable row level security;

-- Users can read only their own records in app contexts.
drop policy if exists "login_events_select_own" on public.login_events;
create policy "login_events_select_own"
  on public.login_events for select
  to authenticated
  using (auth.uid() = user_id);

-- No direct insert/update/delete from client.
drop policy if exists "login_events_no_insert" on public.login_events;
create policy "login_events_no_insert"
  on public.login_events for insert
  to authenticated
  with check (false);

-- Helper to read a request header from PostgREST context.
create or replace function public._request_header(name text)
returns text
language sql
stable
as $$
  select coalesce(
    (current_setting('request.headers', true)::json ->> lower(name)),
    (current_setting('request.headers', true)::json ->> name)
  )
$$;

-- Security definer RPC to write login event with server-side timestamp and request metadata.
create or replace function public.log_login_event(p_user_id uuid, p_email text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_ip_text text;
  v_ip inet;
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;

  if v_uid <> p_user_id then
    raise exception 'user mismatch';
  end if;

  v_ip_text := split_part(coalesce(public._request_header('x-forwarded-for'), ''), ',', 1);
  if nullif(trim(v_ip_text), '') is not null then
    begin
      v_ip := trim(v_ip_text)::inet;
    exception
      when others then
        v_ip := null;
    end;
  end if;

  insert into public.login_events(user_id, email, ip, user_agent)
  values (
    p_user_id,
    p_email,
    v_ip,
    public._request_header('user-agent')
  );
end;
$$;

revoke all on function public.log_login_event(uuid, text) from public;
grant execute on function public.log_login_event(uuid, text) to authenticated;
